# Performing Principal Component Analysis (PCA) - Lab

## Introduction

Now that you have a high-level overview of PCA, as well as some of the details of the algorithm itself, it's time to practice implementing PCA on your own using the NumPy package. 

## Objectives

You will be able to:
    
* Implement PCA from scratch using NumPy

## Import the data

- Import the data stored in the file `'foodusa.csv'` (set `index_col=0`)
- Print the first five rows of the DataFrame 

In [1]:
import pandas as pd
data = pd.read_csv('foodusa.csv',index_col=0)

data.head()

Bread  Burger  Milk  Oranges  Tomatoes
City                                             
ATLANTA     24.5    94.5  73.9     80.1      41.6
BALTIMORE   26.5    91.0  67.5     74.6      53.3
BOSTON      29.7   100.8  61.4    104.0      59.6
BUFFALO     22.8    86.6  65.3    118.4      51.2
CHICAGO     26.7    86.7  62.7    105.9      51.2

## Normalize the data

Next, normalize your data by subtracting the mean from each of the columns.

In [6]:
data = data-data.mean()
data

Bread     Burger       Milk    Oranges   Tomatoes
City                                                               
ATLANTA       -0.791304   2.643478  11.604348 -22.891304  -7.165217
BALTIMORE      1.208696  -0.856522   5.204348 -28.391304   4.534783
BOSTON         4.408696   8.943478  -0.895652   1.008696  10.834783
BUFFALO       -2.491304  -5.256522   3.004348  15.408696   2.434783
CHICAGO        1.408696  -5.156522   0.404348   2.908696   2.434783
CINCINNATI     0.008696  10.643478   1.004348  -3.691304  -3.165217
CLEVELAND     -2.491304  -3.056522  -9.895652   7.908696  -1.965217
DALLAS        -1.991304  -6.356522   0.204348  14.908696  -6.965217
DETROIT       -1.191304   1.843478 -10.795652   6.708696   3.634783
HONALULU       4.008696  14.043478  17.904348  30.208696  12.934783
HOUSTON       -2.991304  -8.256522   5.504348   5.608696  -6.365217
KANSAS CITY    0.808696  -2.956522   3.104348  -2.091304  -5.565217
LOS ANGELES    1.608696  -2.556522  -6.095652 -20.291304 -10.365217
MILWAUKEE     -4.991304  -2.256522  -8.495652   8.808696   5.134783
MINNEAPOLIS   -0.691304   0.343478 -10.395652   3.008696   1.934783
NEW YORK       5.508696  18.843478   3.704348   4.308696  13.834783
PHILADELPHIA  -0.791304   0.443478   4.404348  -4.991304  12.934783
PITTSBURGH     0.908696   3.543478  -2.095652  14.108696   0.534783
ST LOUIS       1.208696   0.543478  -1.495652  12.108696  -2.565217
SAN DIEGO      0.208696  -8.156522  -5.295652 -10.191304 -13.365217
SAN FRANCISCO  1.008696  -4.756522  -3.995652  -1.191304  -7.265217
SEATTLE       -2.791304 -14.156522  -0.295652 -11.891304  -3.865217
WASHINGTON DC -1.091304   1.943478   3.704348 -21.391304  -2.565217

## Calculate the covariance matrix

The next step is to calculate the covariance matrix for your normalized data. 

In [7]:
import numpy as np

In [13]:
cov_mat = data.cov()
cov_mat

Bread     Burger       Milk     Oranges   Tomatoes
Bread      6.284466  12.910968   5.719051    1.310375   7.285138
Burger    12.910968  57.077115  17.507530   22.691877  36.294783
Milk       5.719051  17.507530  48.305889   -0.275040  13.443478
Oranges    1.310375  22.691877  -0.275040  202.756285  38.762411
Tomatoes   7.285138  36.294783  13.443478   38.762411  57.800553

## Calculate the eigenvectors

Next, calculate the eigenvectors and eigenvalues for your covariance matrix. 

In [14]:
eig_values, eig_vectors = np.linalg.eig(cov_mat)
eig_values, eig_vectors

(array([218.99867893,  91.72316894,   3.02922934,  20.81054128,
         37.66268981]),
 array([[-0.02848905, -0.16532108, -0.96716354, -0.18972574,  0.02135748],
        [-0.2001224 , -0.63218494,  0.24877074, -0.65862454,  0.25420475],
        [-0.0416723 , -0.44215032,  0.03606094,  0.10765906, -0.88874949],
        [-0.93885906,  0.31435473, -0.01521357, -0.06904699, -0.12135003],
        [-0.27558389, -0.52791603, -0.03429221,  0.71684022,  0.36100184]]))

## Sort the eigenvectors 

Great! Now that you have the eigenvectors and their associated eigenvalues, sort the eigenvectors based on their eigenvalues to determine primary components!

In [15]:
# Get the index values of the sorted eigenvalues
e_indices = np.argsort(eig_values)[::-1]

# Sort 
eigenvectors_sorted = eig_vectors[:, e_indices]
eigenvectors_sorted

array([[-0.02848905, -0.16532108,  0.02135748, -0.18972574, -0.96716354],
       [-0.2001224 , -0.63218494,  0.25420475, -0.65862454,  0.24877074],
       [-0.0416723 , -0.44215032, -0.88874949,  0.10765906,  0.03606094],
       [-0.93885906,  0.31435473, -0.12135003, -0.06904699, -0.01521357],
       [-0.27558389, -0.52791603,  0.36100184,  0.71684022, -0.03429221]])

## Reprojecting the data

Finally, reproject the dataset using your eigenvectors. Reproject this dataset down to 2 dimensions.

In [16]:
transformed = eigenvectors_sorted.dot(data.T).T
transformed[:2]

array([[ 11.10636706,  14.73134932, -14.17203836,   1.85530932,
        -13.15196933],
       [  1.21900301,  21.44989411,  -7.19007196,  -0.14425049,
        -18.50968283]])

## Summary

Well done! You've now coded PCA on your own using NumPy! With that, it's time to look at further applications of PCA.